[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["find:"]

[tool.setuptools.entry-points.console_scripts]
dirtree2md = "dirtree2md.main:main"
